In [62]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
import csv
import math

In [85]:
# Load data from netlogo's behaviorspace "spreadsheet" output
# ** DIFFERENT THAN THE LOADERS IN OTHER NOTEBOOKS: needs to parse netlogo array
def loadBehaviorspaceAsStrings(filename):
    lines = []
    with open(filename, 'rb') as csvfile:
         reader = csv.reader(csvfile, delimiter=',', quotechar='"')
         for row in reader:
             lines.append(row)

    metadata = lines[0:5]
    
    _data = lines[6:]
    _data = np.array(lines[6:], dtype=object).T
    for i in range(1, len(_data)):
        for j in range(1, len(_data[i])):
            try:
                _data[i][j] = _data[i][j]
            except:
                continue
    data = {}
    for col in _data:
        data[col[0]] = np.array(col[1:], dtype=str)
            
    return (metadata, data)

def parseNetlogoArray(s):
    return eval(s.replace(' ', ', '))

In [152]:
#metadata,data = loadBehaviorspaceAsStrings("./behaviorspace_data/switch-counts-s8_mm0.csv")
metadata,data = loadBehaviorspaceAsStrings("./behaviorspace_data/switch-counts-s0.csv")

In [93]:
def kl(p, q):
    epsilon = 0.0001 # avoid log(0)
    psum = sum(p)*1.0
    qsum = sum(q)*1.0
    pn = [epsilon + pp/psum for pp in p]
    qn = [epsilon + qq/qsum for qq in q]
    ii = [0 if pn[i]==0 else pn[i] * math.log(qn[i]/pn[i]) for i in range(len(p))]
    return -sum(ii)

kl([.68, .10, .22], [.66,.04,.30])

def klcounts(i, j):
    return [counts[i][0], counts[j][0], kl(counts[i][1], counts[j][1])]

In [153]:
#counts = [[6,[75,8,17]],[6,[71,10,19]],[6,[71,5,24]],[6,[76,14,10]],[6,[82,9,9]],[6,[77,8,15]],[6,[78,6,16]],[6,[71,13,16]],[6,[69,4,27]],[6,[71,7,22]],[6,[73,10,17]],[6,[68,7,25]],[6,[78,10,12]],[6,[80,8,12]],[6,[72,7,21]],[6,[78,5,17]],[6,[72,13,15]],[6,[79,10,11]],[6,[68,10,22]],[6,[66,4,30]],[6,[69,12,19]],[6,[77,12,11]],[9,[96,2,2]],[9,[96,2,2]],[9,[96,2,2]],[9,[96,2,2]],[9,[96,2,2]],[9,[98,0,2]],[9,[96,2,2]],[9,[96,2,2]],[9,[96,2,2]],[9,[96,2,2]],[9,[96,2,2]],[9,[96,2,2]],[9,[96,2,2]],[9,[96,2,2]],[9,[96,2,2]],[9,[96,2,2]],[9,[96,2,2]],[9,[96,2,2]],[9,[96,2,2]],[9,[96,2,2]],[9,[96,2,2]],[9,[96,2,2]],[9,[96,2,2]],[9,[96,2,2]],[9,[96,2,2]],[9,[96,2,2]],[9,[96,2,2]],[9,[96,2,2]]]
#counts = [[0, [25, 36, 39]], [0, [31, 35, 34]], [0, [34, 33, 33]], [0, [28, 34, 38]], [0, [34, 37, 29]], [0, [34, 27, 39]], [0, [31, 43, 26]], [0, [42, 31, 27]], [0, [34, 29, 37]], [0, [32, 43, 25]], [0, [33, 38, 29]], [0, [22, 44, 34]], [0, [41, 35, 24]], [0, [35, 34, 31]], [0, [32, 35, 33]], [0, [34, 39, 27]], [0, [34, 38, 28]], [0, [29, 36, 35]], [0, [36, 29, 35]], [0, [32, 34, 34]], [0, [32, 35, 33]], [0, [34, 33, 33]], [0, [29, 33, 38]], [0, [28, 34, 38]], [0, [36, 25, 39]], [0, [34, 34, 32]], [0, [33, 35, 32]], [0, [35, 35, 30]], [0, [31, 36, 33]], [0, [25, 36, 39]], [0, [47, 26, 27]], [0, [33, 29, 38]], [0, [29, 41, 30]], [0, [28, 39, 33]], [0, [35, 28, 37]], [0, [31, 35, 34]], [0, [28, 40, 32]], [0, [33, 36, 31]], [0, [26, 41, 33]], [0, [36, 40, 24]], [0, [40, 27, 33]], [0, [39, 27, 34]], [0, [28, 37, 35]], [0, [30, 41, 29]], [0, [25, 41, 34]], [0, [35, 31, 34]], [0, [41, 33, 26]], [0, [28, 32, 40]], [0, [30, 33, 37]], [0, [33, 35, 32]]]
#counts = parseNetlogoArray(data['[list strategy total-pool-counts] of turtles'][0])

# Switch counts
counts = parseNetlogoArray(data['[list strategy (flatten-2d-array switch-counts) ] of turtles'][0])
counts



[[0, [7, 5, 18, 10, 9, 9, 12, 15, 14]],
 [0, [11, 8, 15, 9, 16, 7, 14, 8, 11]],
 [0, [7, 11, 10, 11, 11, 9, 9, 10, 21]],
 [0, [9, 9, 12, 8, 12, 12, 13, 11, 13]],
 [0, [8, 11, 16, 12, 8, 9, 16, 10, 9]],
 [0, [11, 14, 12, 12, 6, 9, 15, 7, 13]],
 [0, [16, 8, 11, 7, 10, 12, 11, 12, 12]],
 [0, [6, 11, 10, 15, 18, 11, 7, 14, 7]],
 [0, [10, 13, 9, 9, 4, 17, 14, 12, 11]],
 [0, [14, 10, 11, 10, 9, 12, 11, 12, 10]],
 [0, [8, 10, 13, 14, 16, 9, 9, 13, 7]],
 [0, [8, 11, 11, 14, 20, 9, 7, 12, 7]],
 [0, [11, 8, 13, 8, 10, 13, 13, 13, 10]],
 [0, [10, 7, 11, 8, 15, 13, 11, 14, 10]],
 [0, [9, 11, 14, 11, 11, 11, 14, 11, 7]],
 [0, [13, 12, 13, 13, 3, 9, 11, 10, 15]],
 [0, [14, 11, 11, 14, 7, 8, 8, 11, 15]],
 [0, [12, 11, 10, 10, 11, 12, 10, 12, 11]],
 [0, [13, 17, 9, 14, 7, 10, 12, 7, 10]],
 [0, [16, 11, 12, 13, 10, 9, 11, 10, 7]],
 [0, [7, 10, 10, 10, 15, 16, 11, 15, 5]],
 [0, [6, 12, 11, 10, 8, 13, 13, 10, 16]],
 [0, [8, 10, 13, 9, 12, 12, 13, 11, 11]],
 [0, [8, 13, 7, 9, 21, 13, 11, 9, 8]],
 [0, [9, 

In [157]:
[klcounts(i,2) for i in range(len(counts))]

[[0, 0, 0.07807629111415565],
 [0, 0, 0.08299777802996586],
 [0, 0, -0.0],
 [0, 0, 0.042255588089887997],
 [0, 0, 0.08745819427077389],
 [0, 0, 0.06937587758548033],
 [0, 0, 0.0882281012910517],
 [0, 0, 0.10154577919525018],
 [0, 0, 0.11111011880471519],
 [0, 0, 0.07537301558044023],
 [0, 0, 0.08698426923392674],
 [0, 0, 0.10283512448164167],
 [0, 0, 0.07959461962917892],
 [0, 0, 0.07907703651824506],
 [0, 0, 0.08805027648724037],
 [0, 0, 0.08007322179875073],
 [0, 0, 0.05127977801168733],
 [0, 0, 0.051428886463699974],
 [0, 0, 0.09387704352427283],
 [0, 0, 0.11253554213475273],
 [0, 0, 0.13187326401647748],
 [0, 0, 0.029033059366430067],
 [0, 0, 0.049782113618206836],
 [0, 0, 0.10936607964120827],
 [0, 0, 0.07593554723631063],
 [0, 0, 0.10707972229043144],
 [0, 0, 0.15820109607677046],
 [0, 0, 0.03425367657420797],
 [0, 0, 0.13414432753137256],
 [0, 0, 0.17448431013222282],
 [0, 0, 0.12334886784656737],
 [0, 0, 0.08085897602491379],
 [0, 0, 0.1288294077997778],
 [0, 0, 0.1066500847047

In [126]:
t0 = np.array([[0.3348477337293946 ,0.2492191697484356 ,0.4159330965221698] ,[0.21852188295534392 ,0.6067377914256733 ,0.17474032561898278] ,[0.6745432938025806 ,0.19415720110518372 ,0.13129950509223565]])
t15 = np.array([[0.5479161728608479 ,0.11220989031515999 ,0.33987393682399203] ,[0.3676927397531416 ,0.4689933690264956 ,0.16331389122036297] ,[0.2116228106427906 ,0.14559950773860508 ,0.6427776816186043]])
t36 = np.array([[0.14452393905774974, 0.4553052368034887, 0.4001708241387616], [0.6169382714694017, 0.13023149799852465, 0.25283023053207365], [0.14629665879806025, 0.612147359080162, 0.2415559821217777]])

In [117]:
t0

array([[0.33484773, 0.24921917, 0.4159331 ],
       [0.21852188, 0.60673779, 0.17474033],
       [0.67454329, 0.1941572 , 0.13129951]])

In [120]:
t15

array([[0.54791617, 0.11220989, 0.33987394],
       [0.36769274, 0.46899337, 0.16331389],
       [0.21162281, 0.14559951, 0.64277768]])

In [127]:
t36

array([[0.14452394, 0.45530524, 0.40017082],
       [0.61693827, 0.1302315 , 0.25283023],
       [0.14629666, 0.61214736, 0.24155598]])

In [132]:
np.linalg.eig(t0)

(array([-0.30468857,  1.        ,  0.3775736 ]),
 array([[ 0.53574754, -0.57735027,  0.40323416],
        [ 0.03330989, -0.57735027, -0.76611825],
        [-0.84372094, -0.57735027,  0.50046482]]))

In [133]:
np.linalg.eig(t15)

(array([1.        +0.j        , 0.32984361+0.07189935j,
        0.32984361-0.07189935j]),
 array([[ 0.57735027+0.j        ,  0.2494926 -0.27358003j,
          0.2494926 +0.27358003j],
        [ 0.57735027+0.j        , -0.88048393+0.j        ,
         -0.88048393-0.j        ],
        [ 0.57735027+0.j        ,  0.18848677+0.22831599j,
          0.18848677-0.22831599j]]))

In [134]:
np.linalg.eig(t36)

(array([ 1.        +0.j        , -0.24184429+0.12720877j,
        -0.24184429-0.12720877j]),
 array([[ 0.57735027+0.j       , -0.00603834+0.249669j ,
         -0.00603834-0.249669j ],
        [ 0.57735027+0.j       ,  0.58621786-0.2135541j,
          0.58621786+0.2135541j],
        [ 0.57735027+0.j       , -0.74052157+0.j       ,
         -0.74052157-0.j       ]]))

In [146]:
agents=[38,11,1]
print np.dot(t0.T, np.array(agents))
print np.dot(t15.T, np.array(agents))
print np.dot(t36.T, np.array(agents))

[15.80249789 16.33860136 17.85890075]
[25.07705752  9.5685024  15.35444008]
[12.42452733 19.34629284 18.22917984]
